---
title: "Immune Paper - figures"
author: "Marc A.T. Teunis, PhD"
date: "`r Sys.time()`"
params:
  path_out: !r here::here('inst', 'final_figures_paper') 
  loose_images: !r here::here('inst', 'loose_images') 
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{immuneGrinta}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Packages
```{r}
library(tidyverse)
library(kinetics)
library(immuneGrinta)
library(cowplot)
library(svglite)
```

## Load data for analytes
```{r, panel_lines}
data("data_immune", package = "immuneGrinta")
data_immune
```

## Data checks
```{r}
## included subjects
levels(data_immune$subject)
## protocols in GRINTA!
levels(data_immune$protocol)
## analytes included in this analysis
unique(data_immune$analyte)
## time points measured
levels(data_immune$time)
```

## Missing values
```{r}
naniar::vis_miss(data_immune)
```

## Split data by analyte
```{r}
data_summary <- data_immune %>%
  group_by(protocol, time, analyte) %>%
  summarise(
    mean_conc = mean(concentration, na.rm = TRUE),
    sd = sd(concentration, na.rm = TRUE),
    n = n()) %>%
  arrange(protocol, analyte)
data_summary

data_summary$analyte <- as.factor(data_summary$analyte)
levels(data_summary$analyte)

data_split <- split(data_summary, 
                        droplevels(data_summary$analyte))
```

### Load analyte annotations
```{r}
data("analyte_annotations", package = "kinetics")
analyte_annotations
```

## Colours
```{r}
palette <- RColorBrewer::brewer.pal(7, "Set1")
palette <- c(palette[c(1:3,4,5)])
```

## Line plots
```{r, all_lines, eval=TRUE}
image_directory <- params$loose_images
#dir.create(image_directory)

# argument for function test
analytes = data_immune$analyte %>% 
  unique()
immuneGrinta::draw_lines(DF = data_split[[2]], palette_graph = palette)

map(
  .x = data_split,
  immuneGrinta::draw_lines,
  palette_graph = palette
)


test_lines <- immuneGrinta::print_lines(analyte = analytes[1])
#test_lines
run_plotlist <- function(){
  plot_list <- map(
    .x = analytes, 
    .f = immuneGrinta::print_lines)
  names(plot_list) <- levels(data_summary$analyte)
  names(plot_list)
}

```

## Panels
```{r, panels_plot_list, eval=FALSE}
## test
immuneGrinta::print_lines_panel(analytes[4], x_pos = c(1,3))
```

## Prepare potlist for panels
```{r, plotlist}
## generate plotlist
analytes_figs <- c(
        
  "LYMFO_ABS_CORR",
  "MONO_ABS",
  "NEUTRO_ABS",
  "EOS_ABS",
  "BASO_ABS",
  "TROMBO"
)

analyte_data <- data_summary %>%
  dplyr::filter(analyte %in% analytes_figs) %>%
  droplevels()

levels(analyte_data$analyte)


# 
# x_pos_list <- list(
#    = c(1,3),
#   "bicarb" = c(1,3),
#   "chloride" = c(1,3),
#   "ery" = c(1,3),
#   "glu_ns" = c(1,2), ## the GLU_NS set has less time points
#   "hb" = c(1,3),
#   "ht" = c(1,3),
#   "insuline" = c(1,3), 
#   "kreat" = c(1,3),
#   "leuco" = c(1,3),
#   "potassium" = c(1,3),
#   "sodium" = c(1,3)
# )
# x_pos_list
# 

panel_plot_list <- map(
  .x = levels(analyte_data$analyte), 
#  .y = x_pos_list,
  .f = immuneGrinta::print_lines_panel,
  x_pos = c(1,3)
  )

# panel_plot_list
## check x_pos for GLU_NS
names(panel_plot_list) <- levels(analyte_data$analyte)
names(panel_plot_list)

## save to disk for use in the package
# usethis::use_data(panel_plot_list)

```

## Final panels

### Figure 1
```{r}

## names(panel_plot_list) <- analytes_figs

p1_a <- panel_plot_list[[analytes_figs[1]]]
p1_b <- panel_plot_list[[analytes_figs[2]]]
p1_c <- panel_plot_list[[analytes_figs[3]]]
p1_e <- panel_plot_list[[analytes_figs[4]]]
p1_d <- panel_plot_list[[analytes_figs[5]]]
p1_f <- panel_plot_list[[analytes_figs[6]]]

## dimensions
height <- 28
width <- 16
resolution <- 600

# https://cran.r-project.org/web/packages/cowplot/vignettes/shared_legends.html

horizontal_label_offset <- -7
vertical_label_offset <- 4
label_size <- 20

figure_1 <- cowplot::plot_grid(p1_a + theme(legend.position="none"),
           p1_b + theme(legend.position="none"),
           p1_c + theme(legend.position="none"),
           p1_d + theme(legend.position="none"),
           p1_e + theme(legend.position="none"),
           p1_f + theme(legend.position="none"),
           align = 'vh',
           labels = c("A", "B", "C", "D", "E", "F"),
           hjust = horizontal_label_offset, 
           vjust = vertical_label_offset,
           ncol = 2,
           label_size = label_size
           )

#cfigure_1


legend_1 <- get_legend(p1_a + theme(legend.position="bottom"))

p_1 <- plot_grid(legend_1, figure_1, nrow = 2, rel_heights = c(0.05, 1))
p_1


##kinetics::save_in_image_directory(filename = "test2.svg", height = 26, width = 7)
ggsave(p_1, filename = file.path(
    params$path_out,
                         paste(Sys.Date(),
                         "fig_1.svg", sep = "_")), 
       height = height/2.2, 
       width = width/1.5, 
       dpi = resolution/2)

ggsave(p_1, filename = file.path(
    params$path_out,
                         paste(Sys.Date(),
                         "fig_1.png", sep = "_")), 
       height = height/2.2, 
       width = width/1.5, 
       dpi = resolution/2)


ggsave(p_1, filename = file.path(
    params$path_out,
                         paste(Sys.Date(),
                         "fig_1.jpeg", sep = "_")), 
       height = height/2.2, 
       width = width/1.5, 
       dpi = resolution/2)


```
